### ISSUE TITLE
local variable 'current_policy' referenced before assignment

### ISSUE THREAD

**Issue by Guslington** [base2Services/shelvery-aws-backups#138]
## Received event

```
{
    "backup_type": "ebs",
    "action": "create_data_buckets"
}
```

## Stack trace

```
[ERROR] UnboundLocalError: local variable 'current_policy' referenced before assignment
Traceback (most recent call last):
  File "/var/task/shelvery_lambda/lambda_handler.py", line 40, in lambda_handler
    method()
  File "/var/task/shelvery/engine.py", line 417, in create_data_buckets
    if self._bucket_policy_changed(region,bucket.name):
  File "/var/task/shelvery/engine.py", line 94, in _bucket_policy_changed
    return current_policy != shelvery_bucket_policy
```

https://github.com/base2Services/shelvery-aws-backups/blob/8f2d905c763bce3bcf5446f16049592ed1e96429/shelvery/engine.py#L84-L88

**Comment by tarunmenon95** [comment]
As per Shelvery 0.9.7 excepted error is not "NoSuchBucketPolicy" the exception is then raised.
https://github.com/base2Services/shelvery-aws-backups/blob/58667d4f6b22c77bdd956408390026a26c0e9d0c/shelvery/engine.py#L81-L90
